### ISSUE TITLE
Animation transition is not smooth

### ISSUE THREAD

**Issue by 18883234348** [kevancress/MeasureIt_ARCH#168]
![Snipaste_2021-03-31_11-48-51](https://user-images.githubusercontent.com/53850249/113087868-14744780-9217-11eb-9145-ab2562ae1390.jpg)
Font Size and Arrow Size Animation transition is not smooth

**Comment by kevancress** [comment]
Hey @18883234348  Yep this is a known issue,
Font size and Arrow size are both integer properties, so they can't have smooth animation curves. They could be changed to float properties, but that makes them a bit more cumbersome to set for common use cases.

**Comment by kevancress** [comment]
Hey @18883234348  I've found a way to get measureIt-ARCH to treat font size and arrow size as floats for animations, but still display as ints in the UI, If you download the latest development branch it should fix your issue .

Fixed in: abfd7eba24d10478c112ad67b151b5c8122e8ad8 f34bf70d65f85b64c0228a2d700547acccec05de
