### ISSUE TITLE
Object mode is doubling the dimension 

### ISSUE THREAD

**Issue by PeterEller** [kevancress/MeasureIt_ARCH#170]
it's working fine in edit mode but in object mode when I add an aligned dimension between two objects it doubles the value and draws it in the wrong location 

I tried the same task with the basic measureit add-on and it works fine 
I added some screenshots to show the difference

 I'm on mac V 11.2.3 big Sur
 
![Screen Shot 2021-04-12 at 6 32 55 PM](https://user-images.githubusercontent.com/9325215/114484024-5067bf00-9bbe-11eb-8f5c-f3812f9f55e0.png)
![Screen Shot 2021-04-12 at 6 33 10 PM](https://user-images.githubusercontent.com/9325215/114484037-55c50980-9bbe-11eb-8c01-6e424ea22c54.png)

**Comment by kevancress** [comment]
Hi @PeterEller 

Thanks for catching this, I've just added a fix to the main development branch, if you download it dimesnions in object mode should behave as expected.

Also, for more precision you can add dimensions between objects in when in edit mode with multiple objects, this will use the selected vertices rather than defaulting to the objects origin point!

![object dimension fix](https://user-images.githubusercontent.com/16860574/115121184-4d364f80-9f7f-11eb-8886-14f3bfe47beb.gif)

**Comment by PeterEller** [comment]
thanks for the update
Yes I discovered that selecting both objects then going into edit mode allows me to select to vertices  for the align dimension 

Your add-on has been super helpful for my cabinet work!
Will happily pay for it when you have a pro version!

Cheers!

Peter Eller  
MODELLER MODERN SHELF SYSTEM
Direct: +1 (604) 736-5797 | ***@***.*** ***@***.***>
1157 East 23rd Avenue Vancouver, BC, V5V 1Y8
www.modeller.ca <http://www.modeller.ca/>
