### ISSUE TITLE
unable to export image 

### ISSUE THREAD

**Issue by spyro12675** [kevancress/MeasureIt_ARCH#173]
Currently, I'm having a struggle trying to figure out how to export as an image can someone please help

**Comment by kevancress** [comment]
Hey @spyro12675 I just updated the release page with a fix for a bug that was stopping the MeasureIt_ARCH Image rendering from working properly (also fixed in the development branch) Give that a try and let me know if it works!

If it's still having problems exporting re-open this issue and let me know
Thanks!
